name: Update Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Pac-Man Contribution Graph

    steps:
      - uses: actions/checkout@v4
      - uses: tha-rue/gh-action-github-profile-pacman@v2.2.0 
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DIR: output
